[package]
name = "vlam"
version = "0.1.0"
edition = "2024"

[dependencies]
keter = { path = "../sefirot/keter", features = ["glam", "trace"] }
keter_testbed = { path = "../sefirot/testbed", features = ["video"] }
palette = "0.7.6"
